"""Combine human verification notes with the changelog generated by git-cliff."""
import argparse
from pathlib import Path
from version import ROOT, Version


def human_notes(root, info):
    specific = root / "docs/releases" / f"{info.version}.md"
    return specific if specific.is_file() else root / "docs/releases/NOTES.md"


def render(root, info, changes):
    notes = human_notes(root, info).read_text(encoding="utf-8-sig").strip()
    if not notes or not changes.strip():
        raise ValueError("Release notes and generated changelog must both be non-empty")
    return f"# LumaDesk {info.version}\n\n{notes}\n\n## 提交变更\n\n{changes.strip()}\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=ROOT)
    parser.add_argument("--version", required=True)
    parser.add_argument("--changes", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render(args.root, Version.parse(args.version), args.changes.read_text(encoding="utf-8-sig")), encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
